package pluginlobster

// cost.go — the cost ledger and `cost_limit` enforcement.
//
// DIVERGENCE (documented, not silent): upstream lobster maintains a full LLM SPEND
// ledger with replay provenance, because its steps may call a model. This engine's
// stdlib is deterministic by construction — it refuses the LLM pipeline stages — so
// there is nothing for this engine to spend. What it still does, faithfully, is READ
// the `_meta.cost` block a step emits (a charly step's own accounting, produced by
// whatever plugin ran it) and enforce the workflow's `cost_limit` on the total, so a
// workflow that composes an expensive step still cannot run away without the author's
// ceiling firing.
//
// `settle` is upstream's reservation release. There are no in-flight reservations here
// (every step is synchronous and its cost is known when it returns), so it is a no-op
// kept as the named point where the reservation lifecycle WOULD go.

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/opencharly/plugin-lobster/candy/plugin-lobster/params"
)

// stepCost is one step's recorded spend, mirroring upstream's by-step entry.
//
// DIVERGENCE (documented, not silent): the CUE-sourced params.LobsterStepCost types every
// numeric field `any` (its CUE definition is a number disjunction), but the ledger does
// ARITHMETIC on them — accumulate totals, compare against `cost_limit` — so the engine
// holds the projected values TYPED (int64/float64). The generated view is still the ONE
// decode source: track() decodes params.LobsterCostMeta; projectCost projects it here
// through toInt/toFloat, which is where the "not a number" case is decided.
type stepCost struct {
	StepID       string
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostUSD      float64
}

// costSummary is what a run reports back. Same typed-arithmetic divergence as stepCost:
// the params.LobsterCostSummary fields are `any`, the report's are typed.
type costSummary struct {
	TotalInputTokens  int64
	TotalOutputTokens int64
	EstimatedCostUSD  float64
	ByStep            []stepCost
}

// costTracker accumulates the ledger for one run and enforces the ceiling.
type costTracker struct {
	limit    params.LobsterCostLimit
	stderr   io.Writer
	byStep   []stepCost
	totalUSD float64
	warned   bool
}

func newCostTracker(limit params.LobsterCostLimit, stderr io.Writer) *costTracker {
	if stderr == nil {
		stderr = io.Discard
	}
	return &costTracker{limit: limit, stderr: stderr}
}

// track records whatever `_meta.cost` a completed step emitted. A step that reports no
// cost contributes nothing — this is a ledger, not an estimate. The `_meta` block is
// decoded through the CUE-sourced params.LobsterCostMeta rather than hand-read from the
// map, so the ledger reads the same shape the schema documents.
func (c *costTracker) track(stepID string, r *stepResult) {
	if r == nil || !r.HasJSON {
		return
	}
	obj, ok := r.Json.(map[string]any)
	if !ok {
		return
	}
	rawMeta, ok := obj["_meta"]
	if !ok {
		return
	}
	metaMap, ok := rawMeta.(map[string]any)
	if !ok {
		return
	}
	if _, ok := metaMap["cost"]; !ok {
		return
	}
	metaBytes, err := json.Marshal(rawMeta)
	if err != nil {
		return
	}
	var meta params.LobsterCostMeta
	if err := json.Unmarshal(metaBytes, &meta); err != nil {
		return
	}
	// The generated `cost` view is the decode target; projectCost reads it and writes the
	// engine's typed ledger row.
	c.projectCost(stepID, meta.Cost)
}

// projectCost records one step's spend. Its parameter and its by-step local are the
// CUE-sourced shapes (params.LobsterCostSummary / params.LobsterStepCost), so the decode
// contract is NAMED at the seam: a schema change breaks here rather than sliding silently
// through an anonymous value. The row appended is the engine's TYPED projection, whose
// divergence is documented on stepCost above.
func (c *costTracker) projectCost(stepID string, cost params.LobsterCostSummary) {
	entry := stepCost{StepID: stepID}
	// The step's own `model`: upstream's cost shape carries it on each BY-STEP entry,
	// never at the summary level, so the row is taken from the generated by-step entry
	// that names THIS step rather than by position.
	var row params.LobsterStepCost
	for _, bs := range cost.ByStep {
		if bs.StepId == stepID {
			row = bs
			break
		}
	}
	if m, ok := row.Model.(string); ok {
		entry.Model = m
	}
	if n, ok := toInt(cost.TotalInputTokens); ok {
		entry.InputTokens = n
	}
	if n, ok := toInt(cost.TotalOutputTokens); ok {
		entry.OutputTokens = n
	}
	if f, ok := toFloat(cost.EstimatedCostUsd); ok {
		entry.CostUSD = f
	}

	c.byStep = append(c.byStep, entry)
	c.totalUSD += entry.CostUSD
}

// settle is the reservation-release point. See the file header: this engine holds no
// in-flight reservations, so there is nothing to release.
func (c *costTracker) settle() {}

// checkLimit enforces `cost_limit`. The action is upstream's: `stop` fails the run,
// `warn` prints once and continues. An absent limit is no limit.
func (c *costTracker) checkLimit() error {
	maxUSD, ok := toFloat(c.limit.Max_usd)
	if !ok {
		return nil
	}
	if c.totalUSD <= maxUSD {
		return nil
	}
	action := strings.TrimSpace(c.limit.Action)
	if action == "" {
		action = "warn"
	}
	if action == "stop" {
		return fmt.Errorf("Workflow cost limit exceeded: $%.4f > $%.4f", c.totalUSD, maxUSD)
	}
	if !c.warned {
		c.warned = true
		fmt.Fprintf(c.stderr, "[COST] Workflow cost limit exceeded: $%.4f > $%.4f\n", c.totalUSD, maxUSD)
	}
	return nil
}

// summary renders the ledger. A run that spent nothing reports nil rather than a
// zero-valued block, so a caller can tell "no accounting" from "accounted, zero".
func (c *costTracker) summary() *costSummary {
	if len(c.byStep) == 0 {
		return nil
	}
	s := &costSummary{
		EstimatedCostUSD: c.totalUSD,
		ByStep:           append([]stepCost{}, c.byStep...),
	}
	for _, e := range c.byStep {
		s.TotalInputTokens += e.InputTokens
		s.TotalOutputTokens += e.OutputTokens
	}
	return s
}
