// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// ── the workflow file ───────────────────────────────────────────────────────
// #LobsterFile is upstream's WorkflowFile. `steps` is non-empty (load.ts: "Workflow
// file requires a non-empty steps array").
type LobsterFile struct {
	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	// args: name -> {default, description}. Upstream's arg spec is a strict subset of
	// charly's #TaskParamSpec, which is what the engine wire carries.
	Args map[string]struct {
		Default any/* CUE top */ `json:"default,omitempty"`

		Description string `json:"description,omitempty"`
	} `json:"args,omitempty"`

	Env map[string]string `json:"env,omitempty"`

	Cwd string `json:"cwd,omitempty"`

	Steps []LobsterStep `json:"steps"`

	Cost_limit LobsterCostLimit `json:"cost_limit,omitempty"`
}

// ── one step ────────────────────────────────────────────────────────────────
// Exactly one of run | pipeline | workflow | parallel | for_each, OR an approval |
// input gate. load.ts enforces the exclusivity and the counts; the CUE bounds below
// carry the per-field ones (types, enums, numeric ranges) it also enforces.
type LobsterStep struct {
	Id string `json:"id"`

	// the shell arm. `command` is upstream's deprecated ALIAS of `run` (load.ts:
	// `typeof step.run === "string" ? step.run : step.command`) — accepted on import.
	Run string `json:"run,omitempty"`

	Command string `json:"command,omitempty"`

	// the deterministic stdlib arm: a lobster pipeline expression, parsed and run
	// natively (never handed to a shell).
	Pipeline string `json:"pipeline,omitempty"`

	// the sub-workflow arm: a file path to another .lobster file.
	Workflow string `json:"workflow,omitempty"`

	Workflow_args map[string]any/* CUE top */ `json:"workflow_args,omitempty"`

	Parallel LobsterParallel `json:"parallel,omitempty"`

	For_each string `json:"for_each,omitempty"`

	Item_var string `json:"item_var,omitempty"`

	Index_var string `json:"index_var,omitempty"`

	Batch_size int64 `json:"batch_size,omitempty"`

	Pause_ms any/* CUE number; int64 or float64 */ `json:"pause_ms,omitempty"`

	Steps []*LobsterStep `json:"steps,omitempty"`

	Env map[string]string `json:"env,omitempty"`

	Cwd string `json:"cwd,omitempty"`

	Stdin any/* CUE top */ `json:"stdin,omitempty"`

	Approval LobsterApproval `json:"approval,omitempty"`

	Input LobsterInput `json:"input,omitempty"`

	// condition/when: upstream carries both; `when` is the one the runner evaluates
	// (an expression over $id.* refs) and `condition` is the legacy spelling.
	Condition any/* CUE top */ `json:"condition,omitempty"`

	When any/* CUE top */ `json:"when,omitempty"`

	Timeout_ms int64 `json:"timeout_ms,omitempty"`

	On_error string `json:"on_error,omitempty"`

	Retry LobsterRetry `json:"retry,omitempty"`

	// redo: the charly-only conditional BACK-EDGE (see #LobsterRedo). It rides a STEP key
	// because that is the only shape upstream's open loader passes through unchanged: an
	// unknown step key is ignored by upstream, so an exported workflow.lobster stays
	// runnable there (it simply runs every step once), while charly's native engine honours
	// it. This is the operator-ruled route — the retired plugin-pipeline executor carried the
	// same spec in its own wire form.
	Redo LobsterRedo `json:"redo,omitempty"`
}

// ── parallel ────────────────────────────────────────────────────────────────
type LobsterParallel struct {
	Wait string `json:"wait,omitempty"`

	Timeout_ms int64 `json:"timeout_ms,omitempty"`

	Branches []LobsterBranch `json:"branches"`
}

// #LobsterBranch: one parallel branch. Exactly one of run | command | pipeline
// (load.ts: "can only define one of run, command, or pipeline"). A branch has no
// nested steps, no approval and no input — upstream's shape, not a simplification.
type LobsterBranch struct {
	Id string `json:"id"`

	Run string `json:"run,omitempty"`

	Command string `json:"command,omitempty"`

	Pipeline string `json:"pipeline,omitempty"`

	Env map[string]string `json:"env,omitempty"`

	Cwd string `json:"cwd,omitempty"`

	Stdin any/* CUE top */ `json:"stdin,omitempty"`
}

// ── gates ───────────────────────────────────────────────────────────────────
// #LobsterApproval is upstream's union: `true`, the literal "required", a free-form
// prompt string, or the object form. `false` is transcribed as a legal bool because
// upstream's declared type is `boolean` — its runtime predicate isApprovalStep(false)
// is false, so a false gate is simply not a gate; that predicate lives in Go, not here.
type LobsterApproval any /* CUE disjunction: (bool|string|struct) */

// #LobsterInput: the `input` gate. `responseSchema` is a JSON Schema; upstream compiles
// it (compileCached) and rejects an invalid one, which the Go side does with
// cuelang.org/go/encoding/jsonschema.
type LobsterInput struct {
	Prompt string `json:"prompt"`

	ResponseSchema any/* CUE top */ `json:"responseSchema"`

	Defaults any/* CUE top */ `json:"defaults,omitempty"`
}

// ── retry ───────────────────────────────────────────────────────────────────
// #LobsterRetry: the per-step retry policy (load.ts validates each field's type and
// range; `max` is a positive integer, `backoff` the closed two-member enum).
type LobsterRetry struct {
	Max int64 `json:"max,omitempty"`

	Backoff string `json:"backoff,omitempty"`

	Delay_ms any/* CUE number; int64 or float64 */ `json:"delay_ms,omitempty"`

	Max_delay_ms any/* CUE number; int64 or float64 */ `json:"max_delay_ms,omitempty"`

	Jitter bool `json:"jitter,omitempty"`
}

// ── redo ─────────────────────────────────────────────────────────────────────
// #LobsterRedo: the charly-only conditional BACK-EDGE. A failing step emits a trigger on
// its stderr ("LOOP-GUARD-TRIGGER: <name>"); `triggers` maps that name to the id of an
// EARLIER step to re-enter. Upstream lobster has no such key and ignores it, so an exported
// workflow.lobster stays runnable by upstream (it simply runs every step once).
type LobsterRedo struct {
	On_fail any/* CUE disjunction: (string|list) */ `json:"on_fail,omitempty"`

	Triggers map[string]string `json:"triggers,omitempty"`

	Max int64 `json:"max,omitempty"`

	Escalate_after int64 `json:"escalate_after,omitempty"`
}

// ── cost ────────────────────────────────────────────────────────────────────
// #LobsterCostLimit: the workflow-level `cost_limit` (cost_tracker.ts). max_usd is a
// non-negative number and action is the closed {warn, stop} enum.
type LobsterCostLimit struct {
	Max_usd any/* CUE number; int64 or float64 */ `json:"max_usd"`

	Action string `json:"action,omitempty"`
}

// The object form. The snake_case and camelCase spellings are BOTH upstream-legal
// (load.ts validates each independently), hence both are carried.
type LobsterApprovalObject struct {
	Prompt string `json:"prompt,omitempty"`

	Items []any/* CUE top */ `json:"items,omitempty"`

	Preview string `json:"preview,omitempty"`

	Initiated_by string `json:"initiated_by,omitempty"`

	InitiatedBy string `json:"initiatedBy,omitempty"`

	Required_approver string `json:"required_approver,omitempty"`

	RequiredApprover string `json:"requiredApprover,omitempty"`

	Require_different_approver bool `json:"require_different_approver,omitempty"`

	RequireDifferentApprover bool `json:"requireDifferentApprover,omitempty"`
}

// #LobsterApprovalIdentity: the identity triple a completed approval records — the
// same three fields, camelCase only (upstream's WorkflowApprovalIdentity).
type LobsterApprovalIdentity struct {
	InitiatedBy string `json:"initiatedBy,omitempty"`

	RequiredApprover string `json:"requiredApprover,omitempty"`

	RequireDifferentApprover bool `json:"requireDifferentApprover,omitempty"`
}

// ── results ─────────────────────────────────────────────────────────────────
// #LobsterStepResult: one step's recorded outcome.
type LobsterStepResult struct {
	Id string `json:"id"`

	Stdout string `json:"stdout,omitempty"`

	Json any/* CUE top */ `json:"json,omitempty"`

	Approved bool `json:"approved,omitempty"`

	InitiatedBy string `json:"initiatedBy,omitempty"`

	ApprovedBy string `json:"approvedBy,omitempty"`

	Subject any/* CUE top */ `json:"subject,omitempty"`

	Response any/* CUE top */ `json:"response,omitempty"`

	Skipped bool `json:"skipped,omitempty"`

	Error bool `json:"error,omitempty"`

	ErrorMessage string `json:"errorMessage,omitempty"`
}

// #LobsterRunResult: the tool-mode envelope. `status` is the full upstream enum; the
// engine's own wire reply (spec.WorkflowRunReply) maps onto it one-for-one.
type LobsterRunResult struct {
	Status string `json:"status"`

	Output []any/* CUE top */ `json:"output"`

	RequiresApproval LobsterApprovalRequest `json:"requiresApproval,omitempty"`

	RequiresInput LobsterInputRequest `json:"requiresInput,omitempty"`

	// "_meta" is QUOTED deliberately: an unquoted _meta would be a CUE hidden field
	// (not emitted, not generated), which is not what upstream's JSON carries. The
	// @go(Meta) rename is required for the same reason — without it gengotypes derives
	// the UNEXPORTED field name `meta`, which encoding/json cannot populate.
	Meta LobsterCostMeta `json:"_meta,omitempty"`
}

// #LobsterApprovalRequest: the pending-approval block a needs_approval reply carries.
type LobsterApprovalRequest struct {
	Type string `json:"type"`

	Prompt string `json:"prompt"`

	Items []any/* CUE top */ `json:"items"`

	Preview string `json:"preview,omitempty"`

	InitiatedBy string `json:"initiatedBy,omitempty"`

	RequiredApprover string `json:"requiredApprover,omitempty"`

	RequireDifferentApprover bool `json:"requireDifferentApprover,omitempty"`

	ResumeToken string `json:"resumeToken,omitempty"`

	ApprovalId string `json:"approvalId,omitempty"`
}

// #LobsterInputRequest: the pending-input block a needs_input reply carries.
type LobsterInputRequest struct {
	Type string `json:"type"`

	Prompt string `json:"prompt"`

	ResponseSchema any/* CUE top */ `json:"responseSchema"`

	Defaults any/* CUE top */ `json:"defaults,omitempty"`

	Subject any/* CUE top */ `json:"subject,omitempty"`

	ResumeToken string `json:"resumeToken,omitempty"`
}

// #LobsterCostMeta: the `_meta` block (upstream: `{cost?: CostSummary}`).
type LobsterCostMeta struct {
	Cost LobsterCostSummary `json:"cost,omitempty"`
}

// #LobsterCostSummary / #LobsterStepCost: the `_meta.cost` payload.
type LobsterCostSummary struct {
	TotalInputTokens any/* CUE number; int64 or float64 */ `json:"totalInputTokens"`

	TotalOutputTokens any/* CUE number; int64 or float64 */ `json:"totalOutputTokens"`

	EstimatedCostUsd any/* CUE number; int64 or float64 */ `json:"estimatedCostUsd"`

	ByStep []LobsterStepCost `json:"byStep"`
}

type LobsterStepCost struct {
	StepId string `json:"stepId"`

	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	InputTokens any/* CUE number; int64 or float64 */ `json:"inputTokens"`

	OutputTokens any/* CUE number; int64 or float64 */ `json:"outputTokens"`

	CostUsd any/* CUE number; int64 or float64 */ `json:"costUsd"`
}
